homework2
nazlukyanovich/DevIncubator-Base pull request #2
Opened 2021-03-09 13:13 UTC by nazlukyanovich

Homework

2021-03-10 12:34 UTC, AlexanderRusak requested changes

2021-03-10 12:34 UTC, AlexanderRusak commented on fraction.cpp
> +
Incorrect output

2021-03-10 12:34 UTC, AlexanderRusak commented on guessTheNumber.cpp
> +}
Prevent negative numbers from being entered

2021-03-10 12:36 UTC, AlexanderRusak commented on guessTheNumber.cpp
> +}
I've reviewed your tasks, but look more attentively on logic in your applications

2021-03-10 12:36 UTC, AlexanderRusak commented
I've reviewed your tasks, but look more attentively on logic in your applications

2021-03-12 09:52 UTC, nazlukyanovich commented
fixed, thanks

2021-03-17 23:49 UTC, AlexanderRusak approved these changes

2021-03-18 14:52 UTC, merged